### ISSUE TITLE
Listed schema paths not working

### ISSUE THREAD

**Issue by Smolli** [kobylynskyi/graphql-java-codegen-maven-plugin#1]
When putting multiple schema paths and put them each on a new line, the second file will not be found.

    <graphqlSchemaPaths>
        ${graphql.dir}/customer.graphqls,
        ${graphql.dir}/project.graphqls,
        ${graphql.dir}/base.graphqls
    </graphqlSchemaPaths>

Results in:

    java.nio.file.NoSuchFileException: 
    <the dir>/project.graphqls

Putting them all in one line works.

**Comment by kobylynskyi** [comment]
@Smolli, please try the following approach a let me know if it works for you:

```xml
<graphqlSchemaPaths>
    <graphqlSchemaPath>${graphql.dir}/customer.graphqls</graphqlSchemaPath>
    <graphqlSchemaPath>${graphql.dir}/project.graphqls</graphqlSchemaPath>
    <graphqlSchemaPath>${graphql.dir}/base.graphql</graphqlSchemaPath>
</graphqlSchemaPaths>
```

**Comment by kobylynskyi** [comment]
@Smolli please reopen if the above approach will not work for you
