### ISSUE TITLE
Annotate with lombock

### ISSUE THREAD

**Issue by igorng** [kobylynskyi/graphql-java-codegen-maven-plugin#3]
Hello,

Lombok has been quite a standard now when creating POJO. It would be nice if this plugin could use lombok annotation for getters / setters / equal&hash / constructors ;)

**Comment by joffrey-bion** [comment]
I'm not sure I understand the reason why something like this would be useful.

The point of Lombok is to help people *write* (and maintain) classes by keeping the *hand-written* stuff to a minimum, and generate the rest with annotation processing.

Here, we're literally talking about a code generator already, what would be the point for it to generate annotations for Lombok, which would then read these annotations to generate some more code? Why not directly generate the code (like it currently does)?

Or did you mean to use Lombok's annotations in the GraphQL schema as directives?

**Comment by kobylynskyi** [comment]
Agree with @joffrey-bion
Closing the issue.
