### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by JustinBlandford** [kobylynskyi/graphql-java-codegen-maven-plugin#5]
Hi,

I've tried building the example code in order to debug it to see how it hangs together but I don't think it's designed to run (it all compiles but doesn't run as there is no config in there for an in memory Mongo DB and also no Spring Boot plugin to run mvn spring-boot:run).  Is that correct or am I missing something?  I can see the classes being built in the target folder and how it is mapped etc.  I was expecting in the example to see the request being driven through the GraphQLController class:-

   @ResponseBody
    public ExecutionResult execute(@RequestBody ExecutionInput executionInput) throws IOException {
        return graphQL.execute(executionInput);
    }   

I'm struggling to see how that hangs together invoking the autogenerated classes.  Is there a code example anywhere of calling a running graphql endpoint based on the classes that are auto-generated?   Apologies if it is actually doing this already, but if you could point me in the right direction that would be very helpful as I can't see it easily without running it.  Just to add that I have code and the plugin generates the classes as expected (a Query class etc), But I'm trying to find an example of how to use the generated classes to run the GraphQl query.

Thanks.

**Comment by kobylynskyi** [comment]
Hi @JustinBlandford 
Running the example project is fairly simple. You just need to:
1. Compile the code `mvn clean install` - it will generate classes from GraphQL schema as well as the implementation of the mapper classes.
2. Run Mongo DB locally.
3. Make sure that folders with auto-generated classes are marked as _Source Folders_ in your IDE:
<img width="250" alt="Screenshot 2020-04-02 15 19 13" src="https://user-images.githubusercontent.com/2664706/78297861-203f0800-74f6-11ea-8980-e6aef99a58b8.png">

4. Run Application class:
<img width="250" alt="Screenshot 2020-04-02 15 17 33" src="https://user-images.githubusercontent.com/2664706/78297966-5d0aff00-74f6-11ea-89d6-f9073e395368.png">

5. You can then open GraphiQL and execute some queries/mutations:
<img width="250" alt="Screenshot 2020-04-02 15 21 36" src="https://user-images.githubusercontent.com/2664706/78297995-714efc00-74f6-11ea-9778-bf969d89c623.png">

Feel free to reach out to me if you have any further questions.

**Comment by JustinBlandford** [comment]
Thanks  for responding so quickly, very much appreciated.  I'll take a look - I can see now that Spring Boot is assuming the defaults for a Mongo instance running.  What I'm after is to understand how to invoke a call to a GraphQL endpoint via the generated classes.  I've used your plugin with a GraphQL schema that I am working with and can see the Query and Model classes generated n my target folder,  I want to use those autogenerated classes to call the GraphQL endpoint (which is already running) from a Cucumber test so am looking at the best way to do that.   If you have any suggestions on that, it would be much appreciated,

**Comment by kobylynskyi** [comment]
Hi @JustinBlandford 
> I want to use those autogenerated classes to call the GraphQL endpoint (which is already running) from a Cucumber test

If I correctly understood your question, You will need to write a custom serializer of auto-generated POJO classes to GraphQL request. Maybe there is an existing solution for that, but I was not able to find it. 
The intention of this maven plugin is to generate **server-side** classes.
In the future, I plan to extend the plugin and add a support of **client-side** code generation. This will allow users to build a GraphQL request based on the auto-generated classes.

I hope that helps.

**Comment by kobylynskyi** [comment]
@JustinBlandford 
I've opened a feature request to support client-code generation: https://github.com/kobylynskyi/graphql-java-codegen/issues/37
I hope that it is what you are looking for.
